version: '3'
services:
  app:
    platform: linux/x86_64
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 8888:8888
    command: /bin/bash -c 'jupyter lab --ip=0.0.0.0 --no-browser --allow-root'